name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install CPPCheck
      run: sudo apt -y install cppcheck
    - name: Run cppcheck
      run: cppcheck 3_Implementations
